<?xml version="1.0"?>
<package format="3">
  <name>image_fusion</name>
  <version>0.1.0</version>
  <description>Fuse cmd_vel, odom, YOLO detections into a single 320×320 Image.</description>
  <maintainer email="bob4587@naver.com">kimjunsuk</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>yolo_msgs</depend>
  <depend>cv_bridge</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
