/aruco_node:
  ros__parameters:
    marker_size: 0.055
    # aruco_dictionary_id: DICT_5X5_250
    # aruco_dictionary_id: DICT_ARUCO_ORIGINAL
    aruco_dictionary_id: DICT_6X6_250
    # aruco_dictionary_id: DICT_6X6_1000
    image_topic: /camera/image_raw
    camera_info_topic: /camera/camera_info